### ISSUE TITLE
Return Image with boxes? 

### ISSUE THREAD

**Issue by BradFD** [pliablepixels/mlapi#1]
I got this running after fighting with python, keras and tensorflow versions and forcing downgrades on those and it appears to work well now but how do I get the image with the box drawn as a return from the api? 

The api server seems to make a new random hash like name of any remote or local images in the /image directory but that new random name is not specified in the returned json. So if I am serving a lot of requests to it I won't know which image name goes with my request or if there is a way to ask for it from the api. Thanks. Sorry for the novice questions.

**Comment by pliablepixels** [comment]
It’s always easier to run them using a virtualenv. 

The api doesn’t return an image. It returns box dimensions and text. The user is expected to draw their own image box using the meta data if needed.
