### ISSUE TITLE
Training known faces

### ISSUE THREAD

**Issue by rajil** [pliablepixels/mlapi#13]
There seems to be no way to train known faces. The code 'modules/face_train.py' seems to exist, but an example on how to invoke this will be helpful.

**Comment by pliablepixels** [comment]
The face training process should be the same as what you use for local hooks in the ES (outlined in the ES hooks [docs](https://zmeventnotification.readthedocs.io/en/latest/guides/hooks.html#configuring-face-recognition-directories)).

If you are referring to a situation where the ES is running on a server where the ES is not installed, then correct, there isn't a script to initiate training from CLI as that is part of the ES. However, if you do follow the face recognition doc linked above, mlapi will initiate training on first invocation.

Clearly, there is a lot of work pending to align mlapi with the ES local hooks.

**Comment by pliablepixels** [comment]
supported now.
