### ISSUE TITLE
Error executing remote API: Extra data: line 1 column 329 (char 328)

### ISSUE THREAD

**Issue by mfauvain** [pliablepixels/mlapi#24]
Hi, not sure where to start here. I don't know when those errors have started to show up, as it fallback to server when the mlapi server is down, I didn't notice up until now..
I've reinstalled mlapi but no luck.

**Comment by mfauvain** [comment]
Adding debug log
[debug.txt](https://github.com/pliablepixels/mlapi/files/5683570/debug.txt)

**Comment by pliablepixels** [comment]
I'm not sure either. Works for me. Try to update your pyzm library to the latest version.

**Comment by mfauvain** [comment]
I've reinstalled it on the mlapi server, no luck.
However I tried to shutdown the mlapi server and the zmevent server gives the same error so it does not seem to be on the mlapi server side. I've reinstalled zmeventservernotication but same error.
It really look as if the zmeventserver does not 'connect' for some reason.

**Comment by mfauvain** [comment]
ah. found an old bug report (of mine actually) on the zmeventnotification git page where you told me to delete zm_login.json on the server and ... it worked again.

**Comment by gfro84** [comment]
I hate holding back on asking a question, then no sooner do you ask it, you
figure out the answer yourself!

How do you find the coral library compared to yolo? I liked the speed but
yolo on cpu gives me more accurate results, and I didn't really have the
need for speed so sent it back.

**Comment by pliablepixels** [comment]
Faster but less accurate. However check out the work @rabsym has done on retraining models. He did It for yolo but the same approach applies to coral models too.

**Comment by mfauvain** [comment]
@gfro84 : indeed...
did not try CORAL yet. I am happy with yolo though.

**Comment by pliablepixels** [comment]
closing as the core issue seems to be resolved.
