### ISSUE TITLE
missing yolov3_classes.txt

### ISSUE THREAD

**Issue by mfauvain** [pliablepixels/mlapi#28]
Hi, just updated the mlapi server and for some reason had this file `yolov3_classes.txt` missing in the yolov3 folder. Found it somewhere googling it and added it. now works perfect.
Not sure if I missed a step on my side (did install requirements.txt and getmodels.sh), reporting it just in case.

**Comment by pliablepixels** [comment]
yolov3_classes.txt was used in an older release. The new file is called coco.names. If your install requires yolov3_classes.txt it would be an old version.

**Comment by pliablepixels** [comment]
Ah, found the issue. The default value is yolov3_classes.txt
