### ISSUE TITLE
remote ML requirements question

### ISSUE THREAD

**Issue by repomanz** [pliablepixels/mlapi#29]
Hello -

I have been using dlandon's zoneminder container which up until recently included ES/ML options.  I had these working well but he's decided to drop hooks / ml from his container but is keeping ES.  Therefore I need to stand up a remote ML server to work along side his container so I can continue to do object detection.

I have a fresh Ubuntu 20.04 server stood up but what's not 100% clear to me is what specifically is required to standup a remote machine learning host.  I have gone through your es/ms installation documentation as well as your mlapi documentation.

I believe I do require the mlapi project you have here (to handle the remote side of this) but looking through it, like for example the adding user part, it's looking for a db which doesn't natively exist with just mlapi.  Therefore I assume that I need to do some basic installation of es/ml from your zmeventnotification project.

I have also looked at the zmeventnotification project, specifically around ES/ML installation and know the install script there will prompt me if I want things like ES/hooks/ml.

So, could you let me know a basic outline of what is required to stand up a remote ML server based on your two projects?  Would love to get this going again.  It was working great in his container but now I need to stand up a remote ml server to continue my object detection.  The ml_sequence stuff was working great!

**Comment by repomanz** [comment]
example of mlapi add user script

documentation:
```
Running

Before you run, you need to create at least one user. Use python3 mlapi_adduser.py for that
```

command / error:
`jonjames@vmubntml:/var/lib/zmeventnotification/mlapi$ sudo mlapi_adduser.py
sudo: mlapi_adduser.py: command not found
jonjames@vmubntml:/var/lib/zmeventnotification/mlapi$ sudo python3 mlapi_adduser.py
Traceback (most recent call last):
  File "mlapi_adduser.py", line 8, in <module>
    db = Database.Database()
  File "/var/lib/zmeventnotification/mlapi/modules/db.py", line 12, in __init__
    db = g.config['db_path']+'/db.json'
KeyError: 'db_path'
`
content of mlapiconfig.ini:
`
# folder where the user DB will be stored
db_path=./db
`
db path:
`jonjames@vmubntml:/var/lib/zmeventnotification/mlapi/db$ ls -l
total 0
-rw-r--r-- 1 www-data www-data 0 Jan  9 17:12 empty
`

**Comment by belljaf88** [comment]
Hi, I am coming to MLAPI for the same reason as you and have come across the same issue when I run 

`python3 mlapi_adduser.py `

did you manage to resolve this?

**Comment by repomanz** [comment]
nope - I was hoping dev was going to answer but they haven't yet.  My gut feel is that MLAPI isn't currently architectured to be stand alone.

**Comment by pliablepixels** [comment]
I've just fixed the bug related to mlapi_adduser.py. 
As for the rest, the documentation is pretty straightfoward. mlapi is architected to be standalone from ZM.

**Comment by repomanz** [comment]
Hi @pliablepixels  thanks for responding.  I'll give this a go; thanks for fixing and clarifying.

**Comment by belljaf88** [comment]
Thanks, that’s fixed it. Now to try and figure out how to get the event server (running in dlandon’s docker) to connect to mlapi...
