### ISSUE TITLE
show_percent=no not taken into account by mlapi

### ISSUE THREAD

**Issue by mfauvain** [pliablepixels/mlapi#31]
Hi, it seems objectconfig.ini show_percent=no is not taken into account by the mlapi server. Images are shown with detected object and % when analyzed by mlapi.

**Comment by pliablepixels** [comment]
mlapi only overrides ml_sequence. `show_percent` is outside of it, which means it needs to be part of objectconfig.ini

**Comment by mfauvain** [comment]
not sure I follow. On my zmevent server I have objectconfig.ini with `show_percent=no`. However, when an object detection is run on the mlapi server, the image shown in zmninja has the %. This is new since last upgrade. It was not showing % before.

**Comment by pliablepixels** [comment]
Not sure why. I just tried and it removed the %.

**Comment by pliablepixels** [comment]
Aha I think you mean the percent shows in the bounding boxes correct? I was looking at the message in notification. Yes, that is correct, and will be fixed.

**Comment by mfauvain** [comment]
indeed! Thx

**Comment by pliablepixels** [comment]
Fixed (you need to update zm_detect)
