### ISSUE TITLE
platerecognizer chosen image quality

### ISSUE THREAD

**Issue by cuenhk** [pliablepixels/mlapi#35]
Hi, 

When uploading images to platerecognizer the image quality appears poor, and therefore plates are unreadable.

What the stills capture:
![4k-image-alarm](https://user-images.githubusercontent.com/33085248/108603812-f73f9400-73a1-11eb-8bc8-4150a93fed76.jpg)

What platerecognizer.com receives:
![pa-image-alarm](https://user-images.githubusercontent.com/33085248/108603849-2950f600-73a2-11eb-8bbe-3835c9c501d6.jpg)

I've run a test by posting the alarm image from this recording to platerecognizer and it picked it up (albeit mistaking 1 character) but the quality on there was much better, and readable. 

Hopefully i have the right location o post this - wondering what i can do to force it to post the best image to use?

**Comment by pliablepixels** [comment]
The API has a 3MB limit https://app.platerecognizer.com/upload-limit/
If you want to increase size, you can change the resize parameter in stream_sequence.

**Comment by cuenhk** [comment]
> The API has a 3MB limit https://app.platerecognizer.com/upload-limit/
> If you want to increase size, you can change the resize parameter in stream_sequence.

Perfect, got it. Thank you.
